- job:
    name: grenade-postgresql
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-postgresql/run.yaml
    post-run: playbooks/legacy/grenade-postgresql/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
    irrelevant-files: &grenade-irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$

- job:
    name: grenade-py3
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-py3/run.yaml
    post-run: playbooks/legacy/grenade-py3/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
    irrelevant-files: *grenade-irrelevant-files

- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - neutron-grenade:
            irrelevant-files: *grenade-irrelevant-files
        - grenade-heat:
            voting: false
            irrelevant-files: *grenade-irrelevant-files
        - grenade-py3
        - neutron-grenade-multinode:
            irrelevant-files: *grenade-irrelevant-files
        - ironic-grenade-dsvm:
            voting: false
            irrelevant-files: *grenade-irrelevant-files
    gate:
      jobs:
        - grenade-py3
        - neutron-grenade:
            irrelevant-files: *grenade-irrelevant-files
        - neutron-grenade-multinode:
            irrelevant-files: *grenade-irrelevant-files
    experimental:
      jobs:
        - grenade-postgresql
        - legacy-grenade-dsvm-neutron-forward:
            irrelevant-files: *grenade-irrelevant-files
        - trove-grenade:
            irrelevant-files: *grenade-irrelevant-files

