#!/usr/bin/env bash

# ``prep-work`` handles the preparations for installing and configuring
# the "work" configuration of DevStack.


# Keep track of the devstack directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# System Preparation
# ==================

# perform cleanup to ensure a clean starting environment
##add a config opt to still do this?
##rm -rf $WORK_DEVSTACK_DIR

# Get DevStack if it doesn't exist
if [[ ! -d $WORK_DEVSTACK_DIR ]]; then
    git_clone $WORK_DEVSTACK_REPO $WORK_DEVSTACK_DIR $WORK_DEVSTACK_BRANCH
fi

# Load up a copy of the downloaded images if not present
if [[ -d $DEST/images ]]; then
    rsync -a $DEST/images/* $WORK_DEVSTACK_DIR/files
fi

# Set up work localrc
if [[ ! -r $WORK_DEVSTACK_DIR/localrc ]]; then
    cat $GRENADE_DIR/devstack.localrc.work >$WORK_DEVSTACK_DIR/localrc
    if [[ -r $GRENADE_DIR/devstack.localrc ]]; then
        $GRENADE_DIR/devstack.localrc >>$WORK_DEVSTACK_DIR/localrc
    fi
fi

# clean up apache config
# essex devstack uses 000-default
# folsom devstack uses horizon -> ../sites-available/horizon
if [[ -e /etc/apache2/sites-enabled/horizon ]]; then
    # Clean up folsom-style
    sudo a2dissite horizon
    sudo service apache2 reload
fi

# Essex-specific prep
if [[ "$START_RELEASE" == "essex" ]]; then
    # python-glanceclient is new for Folsom; to roll back to Essex it
    # must be removed and stable/essex restored in the glance repo
    source $WORK_DEVSTACK_DIR/stackrc
    [[ -d $GLANCECLIENT_DIR ]] && rm -rf $GLANCECLIENT_DIR
    [[ -x /usr/local/bin/glance ]] && sudo rm /usr/local/bin/glance
    PIP=$(which pip)
    if [[ -n "$PIP" ]]; then
		$PIP freeze | grep -q python-glanceclient && sudo $PIP uninstall python-glanceclient
		if [[ -d $GLANCE_DIR ]]; then
			cd $GLANCE_DIR
			git checkout $GLANCE_BRANCH
			setup_develop $GLANCE_DIR
		fi
	fi
fi

