#!/usr/bin/env bash

# ``prep-trunk`` handles the preparations for installing and configuring
# the "trunk" configuration of DevStack.


# Keep track of the devstack directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# System Preparation
# ==================

# perform cleanup to ensure a clean starting environment
##add a config opt to still do this?
#rm -rf $TRUNK_DEVSTACK_DIR

# Get DevStack if it doesn't exist
if [[ ! -d $TRUNK_DEVSTACK_DIR ]]; then
    git_clone $TRUNK_DEVSTACK_REPO $TRUNK_DEVSTACK_DIR $TRUNK_DEVSTACK_BRANCH
fi

# Set up localrc
if [[ ! -r $TRUNK_DEVSTACK_DIR/localrc ]]; then
    cp -p $GRENADE_DIR/devstack.localrc.trunk $TRUNK_DEVSTACK_DIR/localrc
fi

# Load up a copy of the downloaded images if not present
if [[ -d $DEST/images ]]; then
    rsync -a $DEST/images/* $TRUNK_DEVSTACK_DIR/files
fi

# Set up localrc
if [[ ! -r $WORK_DEVSTACK_DIR/localrc ]]; then
    cat $GRENADE_DIR/devstack.localrc.trunk $GRENADE_DIR/devstack.localrc >>$TRUNK_DEVSTACK_DIR/localrc
fi

# clean up apache config
# essex devstack uses 000-default
# folsom devstack uses horizon -> ../sites-available/horizon
if [[ -e /etc/apache2/sites-enabled/000-default ]]; then
    # Clean up folsom-style
    sudo rm /etc/apache2/sites-enabled/000-default
    sudo service apache2 reload
fi

# Set up Screen
# =============

# Get trunk config
source $TRUNK_DEVSTACK_DIR/stackrc

# Create a new named screen to run processes in
screen -d -m -S $SCREEN_NAME -t shell -s /bin/bash
sleep 1
# Set a reasonable statusbar
SCREEN_HARDSTATUS=${SCREEN_HARDSTATUS:-'%{= .} %-Lw%{= .}%> %n%f %t*%{= .}%+Lw%< %-=%{g}(%{d}%H/%l%{g})'}
screen -r $SCREEN_NAME -X hardstatus alwayslastline "$SCREEN_HARDSTATUS"
