#!/usr/bin/env bash

# ``prep-work`` handles the preparations for installing and configuring
# the "work" configuration of DevStack.


# Keep track of the devstack directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# System Preparation
# ==================

# perform cleanup to ensure a clean starting environment
mkdir -p $START_DIR

# check out devstack
git_clone $DEVSTACK_START_REPO $DEVSTACK_START_DIR $DEVSTACK_START_BRANCH

# Set up localrc
cp -p $GRENADE_DIR/devstack.localrc.work $DEVSTACK_START_DIR/localrc

# Set up a symlink to the 'work' DevStack installation
rm -f $GRENADE_DIR/devstack
ln -s $DEVSTACK_START_DIR $GRENADE_DIR/devstack

# clean up apache config
# essex devstack uses 000-default
# folsom devstack uses horizon -> ../sites-available/horizon
if [[ -e /etc/apache2/sites-enabled/horizon ]]; then
    # Clean up folsom-style
    sudo a2dissite horizon
    sudo service apache2 reload
fi

# TODO(dtroyer): Needs to get rid of modern glance command too
#                all command-line libs?  how do we want to handle them?

