#!/usr/bin/env bash

# ``save-state``

echo "*********************************************************************"
echo "Begin $0"
echo "*********************************************************************"

# Clean up any resources that may be in use
cleanup() {
    set +o errexit

    echo "*********************************************************************"
    echo "ERROR: Abort $0"
    echo "*********************************************************************"

    # Kill ourselves to signal any calling process
    trap 2; kill -2 $$
}

# Keep track of the grenade directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# Save databases
# --------------

source $BASE_DEVSTACK_DIR/stackrc
mkdir -p $SAVE_DIR
MYSQL_SERVICES="keystone glance nova cinder"
if grep -q 'connection *= *mysql' /etc/ceilometer/ceilometer.conf; then
    MYSQL_SERVICES+=" ceilometer"
elif grep -q 'connection *= *mongo' /etc/ceilometer/ceilometer.conf; then
    mongodump --db ceilometer --out $SAVE_DIR/ceilometer-dump.$BASE_RELEASE
fi
for db in $MYSQL_SERVICES ; do
    if mysql -uroot -p$MYSQL_PASSWORD -c $db -e ''; then
        mysqldump -uroot -p$MYSQL_PASSWORD $db >$SAVE_DIR/$db.sql.$BASE_RELEASE
    fi
done
neutron_db_names=$(mysql -uroot -p$MYSQL_PASSWORD -e "show databases;" | grep neutron || :)
for neutron_db in $neutron_db_names; do
    mysqldump -uroot -p$MYSQL_PASSWORD $neutron_db >$SAVE_DIR/$neutron_db.sql.$BASE_RELEASE
done

# Save ebtables/iptables
# ----------------------

sudo iptables-save >$SAVE_DIR/iptables.$BASE_RELEASE
sudo ebtables -t broute -L >$SAVE_DIR/ebtables-broute.$BASE_RELEASE
sudo ebtables -t filter -L >$SAVE_DIR/ebtables-filter.$BASE_RELEASE
sudo ebtables -t nat -L >$SAVE_DIR/ebtables-nat.$BASE_RELEASE


set +o xtrace
echo "*********************************************************************"
echo "SUCCESS: End $0"
echo "*********************************************************************"
