#!/usr/bin/env bash

# ``upgrade-tempest``

echo "*********************************************************************"
echo "Begin $0"
echo "*********************************************************************"

cleanup() {
    set +o errexit

    echo "*********************************************************************"
    echo "ERROR: Abort $0"
    echo "*********************************************************************"

    # Kill ourselves to signal any calling process
    trap 2; kill -2 $$
}

trap cleanup SIGHUP SIGINT SIGTERM


# Keep track of the grenade directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Source params
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# This script exits on an error so that errors don't compound and you see
# only the first error that occured.
set -o errexit

# Print the commands being run so that we can see the command that triggers
# an error.  It is also useful for following allowing as the install occurs.
set -o xtrace

# Set for DevStack compatibility
TOP_DIR=$TARGET_DEVSTACK_DIR

cd $TARGET_DEVSTACK_DIR
source $TARGET_DEVSTACK_DIR/stackrc
source $TARGET_DEVSTACK_DIR/openrc
FILES=$TARGET_DEVSTACK_DIR/files

# Get functions from current DevStack
source $TARGET_DEVSTACK_DIR/lib/rpc_backend
source $TARGET_DEVSTACK_DIR/lib/keystone
source $TARGET_DEVSTACK_DIR/lib/nova
source $TARGET_DEVSTACK_DIR/lib/baremetal
source $TARGET_DEVSTACK_DIR/lib/neutron
source $TARGET_DEVSTACK_DIR/lib/tempest

# install_tempest()
install_tempest

# calls upgrade-tempest for specific release
upgrade_project tempest $GRENADE_DIR $BASE_DEVSTACK_BRANCH

OS_USERNAME=admin
# NOTE(maurosr): Set enabled only the projects that we have the upgrade file
# This avoid tempest to run heat tests in a moment that we don't activate it
# during upgrade.
ENABLED_SERVICES=nova,glance,cinder,keystone,swift
configure_tempest

DEST=$DEST_BACKUP

set +o xtrace
echo "*********************************************************************"
echo "SUCCESS: End $0"
echo "*********************************************************************"
