#!/usr/bin/env bash

# ``upgrade-oslo``

# Keep track of the grenade directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# Upgrade Oslo
# ================
cd $TARGET_DEVSTACK_DIR
source $TARGET_DEVSTACK_DIR/stackrc
source $TARGET_DEVSTACK_DIR/lib/oslo

# NOTE(sdague): in transitioning from grizzly to havana devstack we
# have an issue where we've pip installed an old oslo, but we are actually
# handing new oslo from the git tree instead. Due to the *fun* that is
# python library handling, this means if we don't uninstall old olso, nova-manage
# will actually use the wrong one.
sudo pip uninstall -y oslo.config

# calls upgrade-oslo for specific release
upgrade_project oslo $GRENADE_DIR $BASE_DEVSTACK_BRANCH

install_oslo
