#!/usr/bin/env bash

# ``upgrade_packages``

# Keep track of the grenade directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# Upgrade Dependencies
# ====================

# Glance
# Glance client wants warlock < 2
GLANCE_PIPS="jsonschema warlock<2"

# Glance and Nova pin boto to 2.1.1
# oneiric has 2.0.0 and precise has 2.2.2
NOVA_PIPS="boto==2.1.1"

# Horizon requires Django >= 1.4
HORIZON_PIPS=" \
    Django>=1.4 \
    django-appconf \
    django-compressor \
    django-openstack-auth \
    pytz \
"

# Quantum client requirements
QUANTUM_PIPS="pyparsing cliff>=1.1.2 cmd2"

# SQLAlchemy is 0.7.8 ((cinder, nova)
PIPS="$GLANCE_PIPS $HORIZON_PIPS $NOVA_PIPS $QUANTUM_PIPS \
   SQLAlchemy>=0.7.8"

pip_install $PIPS

# APTS="python-beautifulsoup python-wsgi-intercept"
# BeautifulSoup==3.2.0
# wsgi-intercept==0.4

# Install package requirements
if [[ "$os_PACKAGE" = "deb" ]]; then
    apt_get update
    install_package $(get_packages $TRUNK_DEVSTACK_DIR/files/apts)
else
    install_package $(get_packages $TRUNK_DEVSTACK_DIR/files/rpms)
fi
