#!/usr/bin/env bash

# ``upgrade-devstack``

# Keep track of the grenade directory
GRENADE_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $GRENADE_DIR/functions

# Determine what system we are running on.  This provides ``os_VENDOR``,
# ``os_RELEASE``, ``os_UPDATE``, ``os_PACKAGE``, ``os_CODENAME``
# and ``DISTRO``
GetDistro

# Source params
source $GRENADE_DIR/grenaderc

# For debugging
set -o xtrace


# Upgrade DevStack
# ================

# Reconfigure DevStack for Folsom.  Changes include new handling
# for ``ENABLED_SERVICES``

# Translate Services
# ------------------

#WORK_ENABLED_SERVICES=$(source $WORK_DEVSTACK_DIR/stackrc; echo $ENABLED_SERVICES)
#ENABLED_SERVICES=""

# NOOP for now!

# Write new config to trunk DevStack
#echo -e "\nENABLED_SERVICES=$ENABLED_SERVICES" >>$TRUNK_DEVSTACK_DIR/localrc

# Handle Defaults Changes
# -----------------------

# NOOP for now!