#!/usr/bin/env bash

# ``upgrade-keystone``

configure_keystone_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace

    # nothing to see here yet

    # reset to previous state
    $XTRACE
}
