#!/usr/bin/env bash

# ``upgrade-nova``

function configure_nova_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # upgrade rootwrap configs
    configure_nova_rootwrap

    # rolling nova-compute support
    if [[ "$DO_NOT_UPGRADE_SERVICES" =~ "n-cpu" ]]; then
        iniset $NOVA_CONF upgrade_levels compute havana
    fi

   # reset to previous state
    $XTRACE
}
