#!/usr/bin/env bash

# ``upgrade-nova``

function configure_nova_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # upgrade rootwrap configs
    configure_nova_rootwrap

   # reset to previous state
    $XTRACE
}
