#!/usr/bin/env bash

# ``upgrade-horizon``

configure_horizon_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # nothing to see here yet

    # reset to previous state
    $XTRACE
}
