#!/usr/bin/env bash

# ``upgrade-devstack``

function configure_devstack_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # nothing to see here yet
    # reset to previous state
    $XTRACE
}
