#!/usr/bin/env bash

# ``upgrade-swift``

function configure_swift_upgrade(){
    # Print the commands being run so that we can see the command that triggers
    # an error.  It is also useful for following allowing as the install occurs.
    set -o xtrace
    # nothing to see here yet
    set +o xtrace
}
