#!/usr/bin/env bash

# ``upgrade-neutron``

configure_neutron_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # nothing to see here yet
    # reset to previous state
    $XTRACE
}
