#!/usr/bin/env bash

# ``upgrade-tempest``

function configure_tempest_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # nothing to see here yet

    # reset to previous state
    $XTRACE
}
