#!/usr/bin/env bash

# ``upgrade-ceilometer``

configure_ceilometer_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace
    # nothing to see here yet

    # reset to previous state
    $XTRACE
}
