#!/usr/bin/env bash

# ``upgrade-ceilometer``

function configure_ceilometer_upgrade {
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace

    # ensure we have new paste.ini file for api
    cp $CEILOMETER_DIR/etc/ceilometer/api_paste.ini $CEILOMETER_CONF_DIR

    # reset to previous state
    $XTRACE
}
