#!/usr/bin/env bash

# ``upgrade-keystone``

configure_keystone_upgrade(){
    XTRACE=$(set +o | grep xtrace)
    set -o xtrace

    # Ensure we do not try and deploy anything as Apache based
    # services. Icehouse did not do this by default, upgrade
    # testing in Grenade is limited to similar deployment types.
    export KEYSTONE_USE_MOD_WSGI=False

    $XTRACE
}
