#!/usr/bin/env bash

# ``upgrade-neutron``

function configure_neutron_upgrade {
    local xtrace
    xtrace=$(set +o | grep xtrace)
    set -o xtrace

    # Apply new rootwrap l3 and dhcp filters because now we are using haproxy for serving metadata
    sudo cp -f $TARGET_RELEASE_DIR/neutron/etc/neutron/rootwrap.d/dhcp.filters $NEUTRON_CONF_DIR/rootwrap.d/
    sudo cp -f $TARGET_RELEASE_DIR/neutron/etc/neutron/rootwrap.d/l3.filters $NEUTRON_CONF_DIR/rootwrap.d/

    $xtrace
}
