#!/usr/bin/env bash

# ``upgrade-neutron``

function configure_neutron_upgrade {
    local xtrace
    xtrace=$(set +o | grep xtrace)
    set -o xtrace

    # Apply new rootwrap dhcp.filters because of dnsmasq env variable change
    sudo cp -f $TARGET_RELEASE_DIR/neutron/etc/neutron/rootwrap.d/dhcp.filters $NEUTRON_CONF_DIR/rootwrap.d/

    $xtrace
}
